using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;

/// <summary>
/// Handles clicks on TMP <link="..."> regions generated by MBPMarkupParser.
/// Attach this to the same GameObject as the TextMeshProUGUI component.
/// </summary>
[RequireComponent(typeof(TextMeshProUGUI))]
public sealed class HelpCreditsLinkHandler : MonoBehaviour, IPointerClickHandler
{
    private TextMeshProUGUI text;

    public void SetText(TextMeshProUGUI target)
    {
        text = target;
    }

    private void Awake()
    {
        if (text == null)
            text = GetComponent<TextMeshProUGUI>();
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        if (text == null || eventData == null)
            return;

        Camera eventCamera = eventData.pressEventCamera;
        int linkIndex = TMP_TextUtilities.FindIntersectingLink(
            text,
            eventData.position,
            eventCamera);

        if (linkIndex == -1)
            return;

        TMP_LinkInfo linkInfo = text.textInfo.linkInfo[linkIndex];
        string href = linkInfo.GetLinkID();

        if (string.IsNullOrWhiteSpace(href))
            return;

        Application.OpenURL(href);
    }
}
